version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: digitalWeb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 435435
    ports:
      - "5432:5432"
    networks:
      - backend-network

  backend:
    image: liberosis8803/job3m2-backend
    container_name: job3m2_backend_container
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/digitalWeb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 435435
    ports:
      - "8080:8080"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
